### ISSUE TITLE
Compiler error: Can't read a crossterm event and pass into input function

### ISSUE THREAD

**Issue by Gnarus-G** [rhysd/tui-textarea#8]
![image](https://user-images.githubusercontent.com/37311893/215302668-4dc615f6-3da1-4112-aff4-a3ef3e89627d.png)
```toml
tui = { version = "*", features = ["crossterm"] }
tui-textarea = { version = "*", features = ["crossterm"] }
```
