### ISSUE TITLE
the trait `From<KeyEvent>` is not implemented for `tui_textarea::Input`

### ISSUE THREAD

**Issue by rvigo** [rhysd/tui-textarea#9]
Hi, after update the `crossterm` crate to version `0.26.0`, I started getting this error message at `text_area.input()`:
```
the trait `From<KeyEvent>` is not implemented for `tui_textarea::Input`
``` 
My code:
```rust
  pub fn handle(&mut self, key_event: KeyEvent) {
        match key_event {
            KeyEvent {
                code: KeyCode::Esc | KeyCode::Enter | KeyCode::Down | KeyCode::Up,
                ..
            } => self.on_focus = false,
            input => {
                self.text_area.input(input);
                self.buffer = self.text_area.lines()[0].clone()
            }
        }
    }
``` 

the `KeyEvent` is from `crossterm::event::KeyEvent`
It
Cargo.toml:
```toml
[dependencies]
# another non-TUI related deps
tui = "0.19.0" # uses crossterm as default
crossterm = "0.26.0"
tui-textarea = { version = "0.2.0", features = ["crossterm"] }
# another non-TUI related deps
```

It's like the code can't read the `impl From<KeyEvent> for Input` int the `input.rs` class
